#!/usr/bin/env perl -w

BEGIN {
    push @INC, './lib';
}

use strict;

use Polvo;

$ARGV[0] || &help;

my $polvo = Polvo->new(Config => $ARGV[0]);

$polvo->run();

sub help {
    print "usage: polvo configfile\n\n";
    print "man Polvo for configuration format\n";
    exit 0;
}


